footer:
  path_link: "https://www.railstutorial.org/"
  path_link1: "https://news.railstutorial.org/"
home:
  path_link: "https://www.railstutorial.org/"
help:
 path_link: "https://www.railstutorial.org/help"
contact:
  path_link: "https://www.railstutorial.org/contact"
about:
  path_link: "https://rubyonrails.org/"
